### ISSUE TITLE
cannot  git lfs checkout

### ISSUE THREAD

**Issue by mathpopo** [facebookresearch/mobile-vision#10]
Skipped checkout for "ChamNet/models/ChamNet-A/fp32/model.pb", content not local. Use fetch to download.
Skipped checkout for "ChamNet/models/ChamNet-A/fp32/model_init.pb", content not local. Use fetch to download.
Skipped checkout for "ChamNet/models/ChamNet-A/int8/model.pb", content not local. Use fetch to download.
Skipped checkout for "ChamNet/models/ChamNet-A/int8/model_init.pb", content not local. Use fetch to download.
Skipped checkout for "ChamNet/models/ChamNet-B/fp32/model.pb", content not local. Use fetch to download.
Skipped checkout for "ChamNet/models/ChamNet-B/fp32/model_init.pb", content not local. Use fetch to download.
Skipped checkout for "ChamNet/models/ChamNet-B/int8/model.pb", content not local. Use fetch to download.
Skipped checkout for "ChamNet/models/ChamNet-B/int8/model_init.pb", content not local. Use fetch to download.
Skipped checkout for "ChamNet/models/ChamNet-C/fp32/model.pb", content not local. Use fetch to download.
Skipped checkout for "ChamNet/models/ChamNet-C/fp32/model_init.pb", content not local. Use fetch to download.
Skipped checkout for "ChamNet/models/ChamNet-C/int8/model.pb", content not local. Use fetch to download.
Skipped checkout for "ChamNet/models/ChamNet-C/int8/model_init.pb", content not local. Use fetch to download.
Skipped checkout for "ChamNet/models/ChamNet-D/fp32/model.pb", content not local. Use fetch to download.
Skipped checkout for "ChamNet/models/ChamNet-D/fp32/model_init.pb", content not local. Use fetch to download.
Skipped checkout for "ChamNet/models/ChamNet-D/int8/model.pb", content not local. Use fetch to download.
Skipped checkout for "ChamNet/models/ChamNet-D/int8/model_init.pb", content not local. Use fetch to download.
Skipped checkout for "ChamNet/models/ChamNet-E/fp32/model.pb", content not local. Use fetch to download.
Skipped checkout for "ChamNet/models/ChamNet-E/fp32/model_init.pb", content not local. Use fetch to download.
Skipped checkout for "ChamNet/models/ChamNet-E/int8/model.pb", content not local. Use fetch to download.
Skipped checkout for "ChamNet/models/ChamNet-E/int8/model_init.pb", content not local. Use fetch to download.
Skipped checkout for "ChamNet/models/ChamNet-F/fp32/model.pb", content not local. Use fetch to download.
Skipped checkout for "ChamNet/models/ChamNet-F/fp32/model_init.pb", content not local. Use fetch to download.
Skipped checkout for "ChamNet/models/ChamNet-F/int8/model.pb", content not local. Use fetch to download.
Skipped checkout for "ChamNet/models/ChamNet-F/int8/model_init.pb", content not local. Use fetch to download.
Skipped checkout for "FBNet/models/FBNet-96/fp32/model.pb", content not local. Use fetch to download.
Skipped checkout for "FBNet/models/FBNet-96/fp32/model_init.pb", content not local. Use fetch to download.
Skipped checkout for "FBNet/models/FBNet-96/int8/model.pb", content not local. Use fetch to download.
Skipped checkout for "FBNet/models/FBNet-96/int8/model_init.pb", content not local. Use fetch to download.
Skipped checkout for "FBNet/models/FBNet-A/fp32/model.pb", content not local. Use fetch to download.
Skipped checkout for "FBNet/models/FBNet-A/fp32/model_init.pb", content not local. Use fetch to download.
Skipped checkout for "FBNet/models/FBNet-A/int8/model.pb", content not local. Use fetch to download.
Skipped checkout for "FBNet/models/FBNet-A/int8/model_init.pb", content not local. Use fetch to download.
Skipped checkout for "FBNet/models/FBNet-B/fp32/model.pb", content not local. Use fetch to download.
Skipped checkout for "FBNet/models/FBNet-B/fp32/model_init.pb", content not local. Use fetch to download.
Skipped checkout for "FBNet/models/FBNet-B/int8/model.pb", content not local. Use fetch to download.
Skipped checkout for "FBNet/models/FBNet-B/int8/model_init.pb", content not local. Use fetch to download.
Skipped checkout for "FBNet/models/FBNet-B1/fp32/model.pb", content not local. Use fetch to download.
Skipped checkout for "FBNet/models/FBNet-B1/fp32/model_init.pb", content not local. Use fetch to download.
Skipped checkout for "FBNet/models/FBNet-B1/int8/model.pb", content not local. Use fetch to download.
Skipped checkout for "FBNet/models/FBNet-B1/int8/model_init.pb", content not local. Use fetch to download.
Skipped checkout for "FBNet/models/FBNet-C/fp32/model.pb", content not local. Use fetch to download.
Skipped checkout for "FBNet/models/FBNet-C/fp32/model_init.pb", content not local. Use fetch to download.
Skipped checkout for "FBNet/models/FBNet-C/int8/model.pb", content not local. Use fetch to download.
Skipped checkout for "FBNet/models/FBNet-C/int8/model_init.pb", content not local. Use fetch to download.
Skipped checkout for "FBNet/models/FBNet-C1/fp32/model.pb", content not local. Use fetch to download.
Skipped checkout for "FBNet/models/FBNet-C1/fp32/model_init.pb", content not local. Use fetch to download.
Skipped checkout for "FBNet/models/FBNet-C1/int8/model.pb", content not local. Use fetch to download.
Skipped checkout for "FBNet/models/FBNet-C1/int8/model_init.pb", content not local. Use fetch to download.
Skipped checkout for "runtime_lut/data/SM-G950U-7.0-24-op_lut_database.json.zip", content not local. Use fetch to download.
Checking out LFS objects: 100% (49/49), 296 MB | 0 B/s, done.

**Comment by newstzpz** [comment]
Thanks. We have switched to a different file hosting and fixed the issue.
