### ISSUE TITLE
error git lfs fetch

### ISSUE THREAD

**Issue by mathpopo** [facebookresearch/mobile-vision#11]
git lfs fetch
fetch: Fetching reference refs/heads/master
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/facebookresearch/mobile-vision.git/info/lfs'

**Comment by newstzpz** [comment]
Thanks. We have switched to a different file hosting and fixed the issue.
