### ISSUE TITLE
Errors when run example

### ISSUE THREAD

**Issue by MisakaMikt** [facebookresearch/mobile-vision#128]
I installed repo with command `python setup.py install` successfully. Then use  `python run_fbnet_v2.py` but found errors as following:

![image](https://user-images.githubusercontent.com/52710739/201852131-f283f2e2-2913-46f7-9a80-32655fd16454.png)

I try to import mobile_cv but found no class or functions to use. Is there any probloms during installation? 
My env: Python3.9 + torch1.9.1 + cuda11.1

![image](https://user-images.githubusercontent.com/52710739/201853401-d8bb1f20-7ac1-4885-b57f-886e88adc11f.png)

**Comment by wat3rBro** [comment]
Could you try running from root dir? eg. `python3 -m examples.run_fbnet_v2` as shown in https://github.com/facebookresearch/mobile-vision/blob/main/examples/run_fbnet_v2.py#L8

**Comment by MisakaMikt** [comment]
> Could you try running from root dir? eg. `python3 -m examples.run_fbnet_v2` as shown in https://github.com/facebookresearch/mobile-vision/blob/main/examples/run_fbnet_v2.py#L8


Thank you. Now this example works. For this example, it seems that I misunderstood the difference between running scripts and running modules in Python.

To use it in my code, I directly copy the mobile_cv folder to my project and add its path to `PYTHONPATH`.

However, it seems that the previous installation did not work. I'v tried to learn about module installation or package import rules in Python, but didn't find a solution for that. Do you have any suggestions?

In a word, although the installation seems unsuccessful, I can use it now. Thanks a lot.
