### ISSUE TITLE
No match found in the database.

### ISSUE THREAD

**Issue by ChengTsang** [facebookresearch/mobile-vision#2]
when I use get_runtime.py to look up the latency of some example model such as ChamNet-A, I found some ops not existed : No match found in the database !

**Comment by XiaoliangDai** [comment]
Thank you for your feedback.  We realize that this is due to a caffe2 version mismatch issue.  We will fix it soon.

> when I use get_runtime.py to look up the latency of some example model such as ChamNet-A, I found some ops not existed : No match found in the database !

**Comment by newstzpz** [comment]
Thanks Xiaoliang for fixing it in https://github.com/facebookresearch/mobile-vision/pull/5.
