### ISSUE TITLE
run  example error

### ISSUE THREAD

**Issue by mathpopo** [facebookresearch/mobile-vision#26]
python 3.5  pytorch 1.5.1 cuda9.2

![Screenshot from 2020-07-23 14-22-43](https://user-images.githubusercontent.com/21274466/88257376-23057900-ccf0-11ea-9884-9231ee6e5fcd.png)
![Screenshot from 2020-07-23 14-22-49](https://user-images.githubusercontent.com/21274466/88257385-2862c380-ccf0-11ea-96ca-dcc8205a0e25.png)

**Comment by newstzpz** [comment]
You may consider using Python 3.6 or above instead as F-string (https://www.python.org/dev/peps/pep-0498/) was not supported before that.

**Comment by mathpopo** [comment]
@newstzpz  ok  thanks
