### ISSUE TITLE
How does FBnet sampled ?

### ISSUE THREAD

**Issue by LamHoCN** [facebookresearch/mobile-vision#3]
Hi guys
Very awesome ~ 
Are you able to give a little more information about when the stochastic super net trained over how do you sample architectures from the distribution  ?

**Comment by Catosine** [comment]
@LamHoCN Hi! I've got some idea about how the structure is sampled.

When you finished searching on the supernet, you would get a set of architecture weights, theta by the authors, for each layer. Then, you would apply softmax with it and get the pseudo-probability for each block to be selected. Then, you would pick one block as your selection w.r.t. to the pseudo-probability.

For example, if you have 5 options for some specific layer and accordingly, you have the theta for that layer as [0.5, 0.3, 0.1, 0.05, 0.05] (softmaxed result). Then, if you pick one of the options w.r.t. the theta for 1000 times, you would receive a result of frequency for each options close to the theta.

GL,

**Comment by newstzpz** [comment]
For every layer with multiple candidates, you could get a probability distribution (e.g., [0.7, 0.2, 0.1] for three candidates) after training, you could randomly sample the candidate based on this distribution, another option is to just pick the one with largest probability.
