### ISSUE TITLE
ModuleNotFoundError: No module named 'mobile_cv.common.fb'

### ISSUE THREAD

**Issue by petoor** [facebookresearch/mobile-vision#47]
Calling `from mobile_cv.common.fb import utils_io`
Raises `ModuleNotFoundError: No module named 'mobile_cv.common.fb'`
Used in : `from d2go.export.d2_meta_arch import patch_d2_meta_arch`

**Comment by zhanghang1989** [comment]
fixed in https://github.com/facebookresearch/mobile-vision/pull/48

**Comment by petoor** [comment]
There is a reference right here : 
https://github.com/facebookresearch/mobile-vision/blob/master/mobile_cv/predictor/model_wrappers.py#L8
